### ISSUE TITLE
This is great

### ISSUE THREAD

**Issue by muschellij2** [jonclayden/divest#1]
This is awesome - I had just bundled dcm2niix binaries (https://github.com/muschellij2/dcm2niir/) in another package I've been using for a few years, but this seems like a much better way!

**Comment by jonclayden** [comment]
Thanks. I actually hadn't come across `dcm2niir` until I spotted it on neuroconductor a few days ago, but while playing around with `dcm2niix` recently I noticed that it was very self-contained, and it's actually not been that hard to adapt it for directly interfacing to R. @neurolabusc has also been very responsive and helpful, which really smoothed the road. I hope it's useful!
