### ISSUE TITLE
Enhancement: sortDicom - additional subdirectories via labelFormat

### ISSUE THREAD

**Issue by nwulms** [jonclayden/divest#3]
Dear Jon,

thank you for providing the divest package.
I tried to use your divest package for sorting DICOM images - the sorting works quite well, but my structure is getting chaotic because for every sequence x participants a folder in the output folder is created. I would like to have it structured like output/sequence/subject_id.

Is it possible to enhance the labelFormat argument? 

For instance setting the labelFormat argument to:

labelFormat = "%p/%n/%k" - puts out output/sequence/subject_id/UID?

Best,

Niklas

**Comment by jonclayden** [comment]
Hi Niklas, and thanks for the suggestion. It makes total sense, but would probably require some changes to the underlying `dcm2niix` code. I'll look into it when I get a bit of time.

**Comment by jonclayden** [comment]
Hi again. The `cppsort` branch now implements more flexible sorting, as you suggested. I will merge it into the mainline shortly, but in the meantime feel free to give it a try! You can install it with (e.g.) `remotes::install_github("jonclayden/divest", "cppsort")`.

**Comment by wulms** [comment]
Hi Jon,

thank you very much! I will give it a try.

**Comment by jonclayden** [comment]
This is now merged into the master branch, and will form part of a new release shortly. Do let me know if you have any feedback!
